### ISSUE TITLE
SSH Key

### ISSUE THREAD

**Issue by MaybachDomei** [ezsystems/launchpad#83]
Hello,

how can i work with the SSH Key from my Mac in the Launchpad?

Thanks
Dominik

**Comment by Plopix** [comment]
Hello,

You don't. That's a bad practice to ssh into docker container, you can docker exec.
Same logic on eZ Launchpad because that's just a docker wrapper.

You do 
`ez enter` or `ez exec` or you also have `ez sfrun $SYMFONYCOMMAND` like `ez sfrun cache:clear` same with composer `ez comprun update` or `install of whatever ;)

Closing the issue in the same time

Thanks!

**Comment by MaybachDomei** [comment]
Thank you!
